name: MFE DEV CI
on:
  push:
    branches: [deploy]
    paths:
      - 'packages/root-config/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    defaults:
      run:
        working-directory: ./packages/root-config

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --if-present
      - run: yarn build --if-present