name: "root-config"
on:
  push:
    branches: [deploy]
    paths:
      - "packages/root-config/**"
      - ".github/workflows/root-config.yaml"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    defaults:
      run:
        working-directory: ./packages/root-config

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --if-present
      - run: yarn build --if-present
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '276.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gsutil -m rsync -d -c -r dist gs://app-muslimpro-test-cicd/root-config/$GITHUB_SHA
      - run: |
          curl -H "Authorization: Bearer $(gcloud auth print-identity-token)" -d '{ "service":"@bitsmedia/root-config","url":"https://storage.googleapis.com/app-muslimpro-test-cicd/root-config/$GITHUB_SHA/bitsmedia-root-config.js" }' -X PATCH https://import-map-deployer-syuuraqtba-uc.a.run.app/import-map.json\?env=test\&skip_url_check -H "Accept: application/json" -H "Content-Type: application/json"
